# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IFnT60mnhjSlTfRj9-fcZcU7Lfs4L06l
"""

! pip install streamlit

# Ask for the user's name
name = input("What is your name? ")

# Greet the user
print(f"Hello, {name}!")